mysql:
 dns: root:zyq4836..@tcp(127.0.0.1:3306)/cut_video_db?charset=utf8&parseTime=True&loc=Local
#datasource:
#  host: 127.0.0.1
#  port: 3306
#  database: cut_video_db
#  username: root
#  password: zyq4836..
#  timeout: 10s